### ISSUE TITLE
Great code but why this bad cropped results?

### ISSUE THREAD

**Issue by juanjullian** [polm/ndl-crop#6]
Hi friend, i just tried your code, it does a really great job. I have plenty of thousands of photohraph to crop in (n35 digitized with camera), but in some images the crop isn't accurate, y can work with the code but i don't have much knowledge, so, where can i start? where could be the error?

Here's some examples

![N35_000011_02 cropped](https://user-images.githubusercontent.com/27698813/157930616-6f4f4dae-c21d-49fa-9f8a-0f49d8ed79b5.jpg)

![N35_000011_02](https://user-images.githubusercontent.com/27698813/157930622-a867c909-bb7b-414c-a63d-a045f02f71cd.jpg)
![N35_000015_06 cropped](https://user-images.githubusercontent.com/27698813/157930625-6fedd9d5-0883-4ec4-a077-8e3320a528f9.jpg)
![N35_000015_06](https://user-images.githubusercontent.com/27698813/157930628-6d542a04-3642-4bc9-9654-b98d81d709f9.jpg)
![N35_000024_03 cropped](https://user-images.githubusercontent.com/27698813/157930630-d53f006d-b5f6-44a3-91ce-fdfba8bc8992.jpg)
![N35_000024_03](https://user-images.githubusercontent.com/27698813/157930637-7c881afd-b547-44e4-901c-048259dae7ed.jpg)
![N35_000030_03 cropped](https://user-images.githubusercontent.com/27698813/157930643-561f4000-5efa-40df-a427-cabcbcab0626.jpg)
![N35_000030_03](https://user-images.githubusercontent.com/27698813/157930644-74127a4a-8650-4194-a0d2-1d34ea01f318.jpg)
![N35_000036_02 cropped](https://user-images.githubusercontent.com/27698813/157930647-3022fe53-4db0-4724-a4c3-8b1fded4a077.jpg)
![N35_000036_02](https://user-images.githubusercontent.com/27698813/157930652-0e07cd53-5399-491e-a85f-9e307f523e1d.jpg)
![N35_000049_01 cropped](https://user-images.githubusercontent.com/27698813/157930654-b2605fa6-d516-44a1-ad59-ceb4da36a8e9.jpg)
![N35_000049_01](https://user-images.githubusercontent.com/27698813/157930658-cc2112df-9e85-43c2-96d9-e8af2e380638.jpg)

![N35_0000003_01 cropped](https://user-images.githubusercontent.com/27698813/157930582-9ca62564-3e81-4162-82c3-51056a7cf6ac.jpg)
![N35_0000003_01](https://user-images.githubusercontent.com/27698813/157930594-1bf5c11c-3237-49df-82f8-c3db96947b20.jpg)
![N35_0000007_02 cropped](https://user-images.githubusercontent.com/27698813/157930605-e01caac8-03c9-4e94-81fd-95c671a48edb.jpg)
![N35_0000007_02](https://user-images.githubusercontent.com/27698813/157930611-3172cef7-2a6f-406b-b94e-ba408acbe5a8.jpg)
![N35_000011_01 cropped](https://user-images.githubusercontent.com/27698813/157930613-867ce649-3e8f-4aac-a4cf-c271a6d43893.jpg)
![N35_000011_01](https://user-images.githubusercontent.com/27698813/157930614-c1ea806c-7b4b-4db1-9ada-7f279b1d8d57.jpg)

Thanks in advance!

**Comment by polm** [comment]
Hey, this is something I did over a weekend years ago, I don't provide this kind of support for it. 

Your crops don't actually look that bad to me, but the main thing is your pictures have a black background, while mine had a whitish one. You probably need to change how thresholding works. 

Good luck with your project.
